import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useAccount } from 'wagmi';
import {Alchemy, Network} from "alchemy-sdk";
import styles from '../styles/Home.module.css';
import axios from 'axios';
import NftCard from "../src/components/NftCard";

const Home: NextPage = () => {
  const { address, isConnected } = useAccount();
  const [alchemy, setAlchemy]: any = useState(null);
  // const [nfts,setNfts]: any = useState([{name: "Rahul",age: 25},{name: "Kumar",age:26}]);
  const [nfts,setNfts]: any = useState([]); 

  // 1.
  // NFT Api => Instantly find, verify, and display any NFT, across all major blockchains.
  // To setup apikey and network which we use in our project
  useEffect(() => {
    const settings = {
      apiKey: "yHh6UKtge7pajgTsuFYIQPHZ4JuDTQ5t", // Replace with your Alchemy API Key.
      network: Network.ETH_GOERLI // Replace with your network.
    };

    const alchemy = new Alchemy(settings);

    setAlchemy(alchemy);
  },[])
  
  // 2.
  // Print total NFT found for a particular owner(address)
  useEffect(() => {
    if (address && isConnected && alchemy) {
      fetchNft(address);
    }
  },[address, isConnected, alchemy])

  async function fetchNft(address: string) {
    const nftsForOwner = await alchemy.nft.getNftsForOwner(address);
    // console.log("nftsForOwner: ", nftsForOwner);
    
    // It will print nft one by one
    for (let index = 0; index < nftsForOwner?.ownedNfts.length; index++) {
      let currentNFT = nftsForOwner?.ownedNfts[index];
      // console.log("currentNFT: ", currentNFT);
      const metadata = await axios(currentNFT?.tokenUri?.raw);
      // console.log("metadata: ", metadata.data);
      setNfts(metadata.data);
      // console.log("nfts:: ", nfts);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Rahul NFTs</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
      </main>
      <hr className={styles.hr}/>
      {nfts ? (<div className={styles.nftsDiv}><NftCard nftObj={nfts}/></div>) : (<div>No NFT</div>)}
    </div>
  );
};

export default Home;
